name: Mage Framework

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Mage Framework Build
    strategy:
      matrix:
        php-versions:
          - 8.3
    env:
      PHP_VERSION: ${{ matrix.php-versions }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Task
        uses: arduino/setup-task@v1

      - name: Build Container
        run: task build

      - name: Install Dependencies
        run: task composer -- install

      - name: Code Analysis
        run: task composer -- analyse

      - name: Code Lint
        run: task composer -- lint

#      - name: Testing
#        run: task composer -- test

#      - name: Slack Notification
#        uses: rtCamp/action-slack-notify@v2
#        if: always()
#        env:
#          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
#          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
#          SLACK_COLOR: ${{ job.status }}
#          SLACK_ICON: https://github.githubassets.com/images/icons/copilot/cp-head-square.png?size=48
#          SLACK_USERNAME: GitHub
#          SLACK_FOOTER: ${{ secrets.SLACK_FOOTER }}
